import Link from "next/link";
import { redirect } from "next/navigation";
import { signOut } from "@/app/auth/actions";
import { euros, getCreatorDashboard } from "@/lib/dashboard";

export const dynamic = "force-dynamic";

const statusLabel = { draft: "Borrador", pending_review: "En revisión", published: "Publicada", rejected: "Requiere cambios", archived: "Archivada" };
const relativeChange = (current: number, previous: number) => previous ? Math.round(((current - previous) / previous) * 100) : current ? 100 : null;

export default async function MyLaunchr({ searchParams }: PageProps<"/mylaunchr">) {
  const [{ uploaded }, dashboard] = await Promise.all([searchParams, getCreatorDashboard()]);
  if (!dashboard.user) redirect("/login");
  const name = dashboard.profile?.full_name || dashboard.user.user_metadata.full_name || dashboard.user.email?.split("@")[0] || "Creador";
  const firstName = String(name).split(" ")[0];
  const initials = String(name).split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const stats = dashboard.stats!;
  const salesChange = relativeChange(stats.currentSales, stats.previousSales);
  const revenueChange = relativeChange(stats.currentRevenueCents, stats.previousRevenueCents);

  return <main className="dashboard"><aside className="sidebar"><Link href="/" className="brand"><span>l</span>launchr</Link><div className="workspace"><div className="avatar">{initials}</div><div><b>{name}</b><small>Creator workspace</small></div><span>⌄</span></div><nav className="side-nav"><a className="active" href="#overview"><i>◫</i> Resumen</a><a href="#landings"><i>◇</i> Mis landings <b>{dashboard.landings.length}</b></a><a href="#ventas"><i>↗</i> Ventas</a><a href="#recursos"><i>◌</i> Recursos</a></nav><div className="sidebar-bottom"><Link href="/mylaunchr/ajustes"><i>⚙</i> Ajustes</Link><form action={signOut}><button className="logout" type="submit">← Cerrar sesión</button></form><Link href="/">← Volver a Launchr</Link></div></aside>
    <section className="dash-content" id="overview"><header className="dash-header"><div><p>Tu espacio de creador</p><h1>Buenos días, {firstName} <span>✦</span></h1></div><Link href="/mylaunchr/subir" className="button button-dark">+ Subir landing</Link></header>{uploaded && <p className="dashboard-notice">Tu landing se ha enviado a revisión. Te avisaremos cuando esté publicada.</p>}{dashboard.error && <p className="dashboard-error">No se han podido cargar todos los datos: {dashboard.error}</p>}
    <div className="stats"><article><span>Ventas totales</span><strong>{stats.totalSales}</strong><small className={salesChange !== null && salesChange >= 0 ? "positive" : "negative"}>{salesChange === null ? "Aún no hay ventas" : `${salesChange >= 0 ? "↑" : "↓"} ${Math.abs(salesChange)}%`} <em>{salesChange === null ? "comparte tus landings" : "últimos 30 días"}</em></small></article><article><span>Ingresos</span><strong>{euros(stats.revenueCents)} </strong><small className={revenueChange !== null && revenueChange >= 0 ? "positive" : "negative"}>{revenueChange === null ? "Aún no hay ingresos" : `${revenueChange >= 0 ? "↑" : "↓"} ${Math.abs(revenueChange)}%`} <em>{revenueChange === null ? "cuando vendas aparecerán aquí" : "últimos 30 días"}</em></small></article><article><span>Visitas a tus landings</span><strong>{stats.totalViews.toLocaleString("es-ES")}</strong><small className="positive">{dashboard.landings.length ? `${dashboard.landings.length} ${dashboard.landings.length === 1 ? "landing publicada" : "landings en tu catálogo"}` : "Aún no has publicado"}</small></article></div>
    <section className="dash-section" id="landings"><div className="dash-section-title"><div><span className="eyebrow">TU CATÁLOGO</span><h2>Mis landings</h2></div>{dashboard.landings.length > 0 && <Link href="/mylaunchr/subir" className="text-link">Subir otra <span>→</span></Link>}</div>{dashboard.landings.length === 0 ? <div className="empty-state"><span>◇</span><h3>Tu catálogo empieza aquí.</h3><p>Sube tu primera landing y envíala a revisión para que pueda aparecer en Launchr.</p><Link href="/mylaunchr/subir" className="button button-dark">Subir mi primera landing <i>↗</i></Link></div> : <div className="listing-grid">{dashboard.landings.map((landing) => <article className="listing" key={landing.id}><div className="listing-thumb dynamic-thumb" style={landing.cover_image_url ? { backgroundImage: `url(${landing.cover_image_url})` } : undefined}>{!landing.cover_image_url && <><span>{landing.title}</span><div className="fake-site"><i /><i /><i /></div></>}</div><div className="listing-info"><div><h3>{landing.title}</h3><span className={`status-${landing.status}`}>{statusLabel[landing.status]}</span></div><div><span>{landing.sales_count} ventas · {landing.view_count} visitas</span><b>{euros(landing.price_cents, landing.currency)}</b></div></div></article>)}<Link href="/mylaunchr/subir" className="upload-card"><span>+</span><b>Subir una nueva landing</b><small>Comparte tu trabajo con el mundo</small></Link></div>}</section>
    <section className="insight" id="ventas"><div><span className="eyebrow">CREATOR INSIGHT</span><h2>{stats.totalSales ? "Tu trabajo está generando impacto." : "Tu próxima venta empieza aquí."}</h2><p>{stats.totalSales ? `Has generado ${euros(stats.revenueCents)} con ${stats.totalSales} ventas confirmadas.` : "Una presentación clara, una demo viva y buenas capturas aumentan las posibilidades de que tu landing destaque."}</p><Link href={dashboard.landings.length ? "#landings" : "/mylaunchr/subir"} className="button button-dark">{dashboard.landings.length ? "Ver mi catálogo" : "Crear landing"} <i>↗</i></Link></div><div className="graph"><div className="graph-bars"><i /><i /><i /><i /><i /><i /><i /></div><strong>{stats.totalSales ? euros(stats.revenueCents) : "0 €"}</strong><span>{stats.totalSales ? "ingresos totales" : "ingresos por ahora"}</span></div></section></section></main>;
}
