import Link from "next/link";
import { getFeaturedLandings } from "@/lib/marketplace";

export const dynamic = "force-dynamic";

export default async function Home() {
  const { landings } = await getFeaturedLandings();
  return <main><nav className="nav shell"><Link href="/" className="brand" aria-label="Launchr inicio"><span>l</span>launchr</Link><div className="nav-links"><Link href="/explorar">Explorar</Link><a href="#como-funciona">Cómo funciona</a><a href="#creadores">Para creadores</a></div><div className="nav-actions"><Link href="/login" className="login">Iniciar sesión</Link><Link href="/login" className="button button-dark">Publicar en Launchr <i>↗</i></Link></div></nav>
    <section className="hero shell"><div className="eyebrow"><span className="dot" /> LANDINGS DISEÑADAS PARA CONVERTIR</div><h1>Tu próxima gran idea<br /><em>merece una gran página.</em></h1><p className="hero-copy">Descubre landing pages únicas, listas para explorar. Diseñadas por creadores independientes para que tu idea se vea increíble desde el día uno.</p><div className="hero-actions"><Link href="/explorar" className="button button-orange">Explorar proyectos <i>↘</i></Link><Link href="/mylaunchr" className="text-link">Soy creador <span>→</span></Link></div><div className="hero-notes"><span><b>Selección</b> de creadores independientes</span><span><b>Contacto</b> directo</span><span><b>100%</b> proyectos reales</span></div><div className="hero-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="sun" /><div className="floating-card"><small>RELEASE 04</small><strong>Build something<br />worth seeing.</strong><div className="mini-line" /><div className="mini-line short" /></div><div className="tape">EARLY ACCESS</div></div></section>
    <section className="catalog" id="explorar"><div className="shell"><div className="section-heading"><div><span className="eyebrow">PROYECTOS DESTACADOS</span><h2>Hechos para<br /><em>destacar.</em></h2></div><Link href="/explorar" className="text-link">Ver catálogo <span>→</span></Link></div>{landings.length ? <div className="template-grid">{landings.map((landing, index) => <Link className="template" href={`/landings/${landing.slug}`} key={landing.id}><div className="template-preview dynamic-template" style={landing.cover_image_url ? { backgroundImage: `url(${landing.cover_image_url})` } : undefined}>{!landing.cover_image_url && <><span className="preview-brand">✦ / {landing.slug}</span><div className="preview-content"><span>{landing.title.toUpperCase()}</span><div /><div /><div /></div><span className="preview-number">0{index + 1}</span></>}</div><div className="template-meta"><div><h3>{landing.title}</h3><p>{landing.category}</p></div><span>Ver proyecto ↗</span></div></Link>)}</div> : <div className="public-empty"><span>✦</span><h3>Los próximos proyectos llegarán pronto.</h3><p>Estamos seleccionando las mejores propuestas de nuestra comunidad de creadores.</p><Link href="/mylaunchr/subir" className="button button-dark">Quiero publicar el mío <i>↗</i></Link></div>}</div></section>
    <section className="creator-banner shell" id="creadores"><div className="creator-sticker">✳</div><div><span className="eyebrow">¿DISEÑAS Y DESARROLLAS?</span><h2>Tu trabajo merece<br />llegar más lejos.</h2></div><div className="creator-side"><p>Sube tus landings, construye tu portfolio y conecta con personas que buscan una mirada como la tuya.</p><Link href="/mylaunchr" className="button button-light">Únete a myLaunchr <i>↗</i></Link></div></section><footer className="shell footer"><Link href="/" className="brand"><span>l</span>launchr</Link><p>Diseñado para los que lanzan.</p><p>© 2026 Launchr</p></footer></main>;
}