import Link from "next/link";
import { notFound } from "next/navigation";
import { getPublicLanding } from "@/lib/marketplace";
import ContactModal from "@/app/components/contact-modal";
import PreviewGallery from "./preview-gallery";

export const dynamic = "force-dynamic";
const roleLabels: Record<string, string> = { creator: "Creador independiente", buyer: "Miembro de Launchr", admin: "Equipo Launchr" };

export default async function LandingPage({ params }: PageProps<"/landings/[slug]">) {
  const { slug } = await params;
  const landing = await getPublicLanding(slug);
  if (!landing) notFound();
  const creator = landing.profiles;
  const creatorSlug = creator?.username || creator?.id;
  const initials = creator?.full_name?.slice(0, 2).toUpperCase() || "L";
  const screenshots = landing.landing_assets.filter((asset) => asset.kind === "screenshot").sort((first, second) => first.position - second.position).map((asset) => ({ url: `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/landing-previews/${asset.path}`, device: asset.device ?? (asset.path.includes("/mobile/") ? "mobile" as const : "desktop" as const) }));
  const coverImage = landing.cover_image_url || (landing.landing_assets.find((asset) => asset.kind === "cover") ? `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/landing-previews/${landing.landing_assets.find((asset) => asset.kind === "cover")?.path}` : null);
  return <main className="landing-detail"><nav className="nav shell"><Link href="/" className="brand"><span>l</span>launchr</Link><Link href="/explorar" className="text-link">← Volver a explorar</Link></nav><section className="landing-hero shell"><div className="landing-copy"><span className="eyebrow"><i className="dot" /> {landing.category.toUpperCase()}</span><h1>{landing.title}</h1><p>{landing.tagline || landing.description || "Una landing lista para explorar."}</p><div className="landing-tags">{landing.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div><div className="landing-author"><div className="avatar">{initials}</div><div><small>{roleLabels[creator?.role ?? "creator"] ?? creator?.role}</small><b>{creator?.full_name || "Creador Launchr"}</b></div></div></div><div className="landing-cover" style={coverImage ? { backgroundImage: `url(${coverImage})` } : undefined}>{!coverImage && <span>{landing.title}</span>}</div></section><section className="landing-body shell"><article className="landing-main-content"><span className="eyebrow">VISTA PREVIA</span><h2>{landing.title}<br /><em>para conocerla mejor.</em></h2><p>{landing.description || landing.tagline || "Una landing cuidada hasta el último detalle."}</p><PreviewGallery title={landing.title} screenshots={screenshots} coverImage={coverImage} /><div className="landing-includes"><div className="includes-heading"><span className="eyebrow">DETALLES DEL PROYECTO</span><p>Explora la propuesta y habla directamente con su creador para conocer el proyecto.</p></div><div className="includes-grid"><div><b>01</b><strong>Diseño responsive</strong><p>Una experiencia cuidada en escritorio, tablet y móvil.</p></div><div><b>02</b><strong>Trabajo del creador</strong><p>Conoce su enfoque, experiencia y forma de trabajar.</p></div><div><b>03</b><strong>Contacto directo</strong><p>Pregunta por disponibilidad, personalización o un proyecto a medida.</p></div></div></div></article><aside className="landing-sidebar"><div className="purchase-card"><span>PRECIO ORIENTATIVO</span><strong>{(landing.price_cents / 100).toFixed(0)} {landing.currency}</strong><p>Referencia aproximada del proyecto. Contacta con el desarrollador para confirmar alcance, disponibilidad y condiciones.</p>{creator?.contact_email ? <ContactModal creatorName={creator.full_name} destinationEmail={creator.contact_email} projectTitle={landing.title} /> : <Link className="button button-dark" href={`/creadores/${creatorSlug || ""}`}>Ver perfil del creador <i>↗</i></Link>}<small>Sin compra online: contacto directo con el creador</small></div>{creatorSlug && <Link href={`/creadores/${creatorSlug}`} className="creator-card"><div className="avatar">{initials}</div><div><span>CREADO POR</span><strong>{creator?.full_name}</strong><p>{creator?.bio || "Conoce su trabajo y experiencia."}</p><small>Ver perfil y contactar ↗</small></div></Link>}</aside></section></main>;
}